### ISSUE TITLE
Install Complete: No Available Ports

### ISSUE THREAD

**Issue by DerrickLamers** [cncjs/cncjs-pi-raspbian#13]
CNCjs is not seeing my serial connection. I have tried all serial ports, rebooted several times, and did to fresh installs but the serial connection is never found.

**Comment by DerrickLamers** [comment]
Update, if the stop the cncjs service and run cncjs manually, it works normal.

**Comment by asilverman-sq** [comment]
Same here.

**Comment by AustinSaintAubin** [comment]
Will have to do some more digging into systemd. Could be a few different issues. Thanks for report.

**Comment by AustinSaintAubin** [comment]
Fixed in latest version script. Looks like it was issue with service path and node serial package.
Let me know if still having issues.

**Comment by AustinSaintAubin** [comment]
Assuming this is resolved.

**Comment by TheEagle13** [comment]
I just did a fresh install using this script, and I have the same issue... "No Ports Available".

My CNC is connected as `/dev/ttyUSB0`
