### ISSUE TITLE
kiosk mode chromium

### ISSUE THREAD

**Issue by jelinj8** [cncjs/cncjs-pi-raspbian#14]
As the kiosk mode browser is starting as root, the screen shows dialog about waiting for cncJS, then it stays black. Adding --no-sandbox option to chromium switches solves this.

**Comment by AustinSaintAubin** [comment]
Will add this flag to chrome.

**Comment by AustinSaintAubin** [comment]
Fixed how kiosk launches, runs under current user now. Please let me know if does not work.

**Comment by zmrdko** [comment]
hello, I have issues with kiosk mode. In setup I will set http://localhost:8000/tablet or http://localhost:8000/tinyweb but after reboot, I get default reboot.
I am using latest fresh raspbian lite installation.

**Comment by jelinj8** [comment]
I had this problem too, but not only in kiosk mode, even external browsers are redirected to main page, so I think it isn't related to this problem.

**Comment by zmrdko** [comment]
using browser I am able to get to particular pendant

**Comment by AustinSaintAubin** [comment]
Looking into this shortly.

**Comment by AustinSaintAubin** [comment]
Looks like this is resolved in latest script.
