### ISSUE TITLE
shopfloor tablet doesn't show up in touchscreen after autostart (Raspi OS Lite)

### ISSUE THREAD

**Issue by thommy884** [cncjs/cncjs-pi-raspbian#21]
Hi there, thanks for this great script! Unfortunately, the shopfloor tablet ui doesn't come up on my touchscreen (5 inch waveshare touchscreen) but only the normal cncjs ui. Changing the URL for the kiosk website to [192.XXX.X.XX]/tablet doesn't change anything. I'm able to access the tablet ui only manually by typing the address into a browser. Any suggestions what to change? Thanks a lot! BTW: system occassionally hangs up and reboots, tested on: RPI 3B+)

**Comment by Smeierstad** [comment]
Change the last chromium-browser command with "chromium-browser --kiosk http://localhost/tablet". You may want to change the URL to whatever you use, but this worked for me. I have not noticed any features missing when testing.
