### ISSUE TITLE
Cant Connect

### ISSUE THREAD

**Issue by MichaelJmad** [cncjs/cncjs-pi-raspbian#22]
Run the setup as it is posted and after a reboot, nothing cant connect it gives an ERR_CONNECTION_REFUSED
Tried to run the CNC command npm etc says command not found please help, 

P.S. thanks for the scripts

**Comment by DAV3103** [comment]
Yup I am having the same problem seems to be NPM

**Comment by MichaelJmad** [comment]
I have been able to get it working some but it's very slow/ not responds...
Note I had to install using the CNCJS for Pi guide and not the script. GIT was having issues the day I was installing so that might have been it.

**Comment by AustinSaintAubin** [comment]
Updated the [cncjs-pi-raspbian](https://github.com/cncjs/cncjs-pi-raspbian) install script.
The [Lite x64](https://downloads.raspberrypi.org/raspios_lite_arm64_latest) edition is now recommended.
Recommended RP4 or greater hardware. 

Works with:
- NodeJS: v18.19.0
- NPM: v9.2.0
