### ISSUE TITLE
Can't install on Raspberry Pi Zero W Rev 1.1

### ISSUE THREAD

**Issue by alexcagliari87** [cncjs/cncjs-pi-raspbian#23]
Hi,
I have the last  Raspberry Pi Zero W Rev 1.1.
The steps are:

1. Using Raspberry Pi Imager v 1.6.2 i choose "Raspberry Pi OS Lite 32 bit"
2. Inserting Micro SD into Raspi
3. Login via SSH
4. Run "sudo apt update"
5. Run "URL="https://raw.githubusercontent.com/cncjs/cncjs-pi-raspbian/master/cncjs_install.sh" curl -sSL ${URL} | bash"

![2022-02-01 13_22_40-pi@laser_ ~](https://user-images.githubusercontent.com/41730211/151968637-b9cfd785-7852-454c-8146-e8142100a956.png)

![2022-02-01 13_22_59-GitHub - cncjs_cncjs-pi-raspbian_ Raspberry PI distribution of CNCjs in a ready ](https://user-images.githubusercontent.com/41730211/151968701-d44d35fc-420d-497b-b993-a16132aa4e3f.png)

![2022-02-01 13_23_15-pi@laser_ ~](https://user-images.githubusercontent.com/41730211/151968716-bd14b96d-3c58-479e-87f8-a47eaae5072c.png)

**First Error**
![2022-02-01 13_25_54-cncjs_cncjs-pi-raspbian_ Raspberry PI distribution of CNCjs in a ready to deploy](https://user-images.githubusercontent.com/41730211/151968730-c862e7e0-16ed-4fa3-bb3f-5a00cf2860b4.png)

**.. but solved**
![2022-02-01 13_32_07-pi@laser_ ~](https://user-images.githubusercontent.com/41730211/151968826-e4db6236-7c3b-4c35-8c1f-772e285c73e2.png)

**The problem is this:**
![2022-02-01 13_33_16-pi@laser_ ~](https://user-images.githubusercontent.com/41730211/151968986-28f4782e-5438-4846-a514-36fde7415a67.png)

At this point i tried to manually install npm using "sudo apt install npm -y".
Now typing "npm -v" i have "7.5.2" output
After i relaunch cncjs installer running only the cnc js installation with this output:
![2022-02-01 15_10_07-pi@laser_ ~](https://user-images.githubusercontent.com/41730211/151983696-92c36442-bc73-4db0-af4a-57f4856c40e6.png)

### Another Attempt (SOLUTION)
_Following the solutions proposed by comqdhb  on this comment (Issue 17) https://github.com/cncjs/cncjs-pi-raspbian/issues/17#issuecomment-866640208  and by aoturoa  on this comment https://github.com/cncjs/cncjs-pi-raspbian/issues/17#issuecomment-754245734   _
1. Fresh Install of Raspberry PI OS Lite version (2020-08-20) 
2. 
```
mkdir node
cd node
wget https://unofficial-builds.nodejs.org/download/release/v10.24.1/node-v10.24.1-linux-armv6l.tar.xz
tar xvfJ node-v10.24.1-linux-armv6l.tar.xz 
sudo cp  -R node-v10.24.1-linux-armv6l/* /usr/local
cd  ..
rm -rf node
```

3. Ran script un-ticking need to install node

Result:
![2022-02-01 16_31_09-pi@laser_ ~](https://user-images.githubusercontent.com/41730211/151998577-bd2971cb-1069-4378-ac5b-89d314a59995.png)

### System Info
```
uname -a
	Linux laser 5.10.92+ #1514 Mon Jan 17 17:35:21 GMT 2022 armv6l GNU/Linux
	
cat /etc/*-release
	PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
	NAME="Raspbian GNU/Linux"
	VERSION_ID="11"
	VERSION="11 (bullseye)"
	VERSION_CODENAME=bullseye
	ID=raspbian
	ID_LIKE=debian
```

**Comment by AustinSaintAubin** [comment]
Thanks for the detailed info.
Just an FYI, I generally don't recommend running CNCjs on the Pi Zero, because of performance issues, but let's take a look.

Looks like the Pi Zero requires a different node binary. Which you installed manually (good).

Looking at your latest output results it looks like CNCjs should be working... i am not sure I understand your current issue, aside for script not handling CNCjs on Raspberry Pi Zero.

**Comment by AustinSaintAubin** [comment]
Might use a Raspberry Pi Zero 2, it uses the same processor architecture as the newer Pis, like the Pi4.

**Comment by DavidJJ** [comment]
Did anyone ever solve this issue?  I'm running into the same problems trying to build a cncjs interface to my TimSav needle cutter.

**Comment by AustinSaintAubin** [comment]
Updated the [cncjs-pi-raspbian](https://github.com/cncjs/cncjs-pi-raspbian) install script.
The [Lite x64](https://downloads.raspberrypi.org/raspios_lite_arm64_latest) edition is now recommended.
Recommended RP4 or greater hardware. 

Works with:
- NodeJS: v18.19.0
- NPM: v9.2.0
