### ISSUE TITLE
How do you navigate in Kiosk mode?

### ISSUE THREAD

**Issue by Sam-OCD** [cncjs/cncjs-pi-raspbian#32]
How do you shut down the machine?

Change back to the CNCjs tab?

Thanks

**Comment by AustinSaintAubin** [comment]
I recommend adding custom commands for task such as rebooting and shutting down.
- System [Reboot] `sudo /sbin/reboot`
- System [Shutdown] `sudo /sbin/shutdown`
- System [Poweroff] `sudo /sbin/poweroff`

Here are some more examples.
![image](https://github.com/user-attachments/assets/187893af-eea9-4cd2-8f1c-76441633f277)
