### ISSUE TITLE
notifications not working

### ISSUE THREAD

**Issue by bipbipbip** [cncjs/cncjs-pi-raspbian#5]
hey,

for example if i click shutdown, not notifications windows opening, only a little N on the upper right

**Comment by AustinSaintAubin** [comment]
???
Consider importing the template I created, [cncjs-app-1.9.15.json](https://raw.githubusercontent.com/cncjs/cncjs-pi-raspbian/master/cncjs-app-1.9.15.json)
You can do that in the settings area.

**Comment by bipbipbip** [comment]
hi, 
thanks for your answer
but i've already done that as explained in your instructions.

i've created a custom command to shutdown (because on your version it don't exist), normally when i click on this command it should have a notification window. but (that's the issue), no notification  appears
