### ISSUE TITLE
Raspbarian Buster for Pi 4

### ISSUE THREAD

**Issue by jratha** [cncjs/cncjs-pi-raspbian#8]
Hi Austin

Ive recently got myself a Pi 4 but it will only work with buster or Noobs 3.1.0, do you have any plans on updating the release for Buster?

**Comment by AustinSaintAubin** [comment]
Sorry for the delayed reply. I hope to update as soon as I order a Pi 4. Also looking at creating a setup script or docker container.

**Comment by AustinSaintAubin** [comment]
Script created, see updated readme and give it a try.
