### ISSUE TITLE
AutoStart the kiosk for the Tablet view

### ISSUE THREAD

**Issue by callis11** [cncjs/cncjs-pi-raspbian#9]
Is it possible to change the code so the kiosk open the tablet URL instead of the tinyweb?

**Comment by AustinSaintAubin** [comment]
> Is it possible to change the code so the kiosk open the tablet URL instead of the tinyweb?

Yes, should just have to edit the openbox script calling Chrome to startup.
`nano /home/pi/.config/openbox/autostart`
look for the URL `http://localhost:8000/tinyweb` and change it to `http://localhost:8000/tablet`
